### PR TITLE
Move out c2cr to autobind

### PR DESCRIPTION
**Pull request by j8r**
- `c2cr` moved to [autobind](https://github.com/j8r/crystal-autobind)
- Add support to LLVM 6.0

Edit: Fixes https://github.com/ysbaddaden/clang.cr/issues/1

### CODE REVIEW

**Comment by ysbaddaden** [comment]
I don't intend to remove the c2cr sample.

Why changing the license to ISC, too? I specifically chose the Apache 2.0 for libraries and projects that may eventually be merged / adopted / used in Crystal (e.g. Shards).

**Comment by j8r** [comment]
I don't mind the license, I change it.
Edit: the two licenses are compatible to each other.

**Comment by j8r** [comment]
c2cr and the clang bindings are two separate projects. Why you don't want to split it out?

**Comment by ysbaddaden** [comment]
It's still a sample to understand how libclang can be used in Crystal in a useful way: how to analyze C headers and generate valid bindings from them. However how `autobind` evolves.

**Comment by j8r** [comment]
I agree on the concept, but adding functionalities to it render it more and more like a true project and less and less than a small sample like [single file samples funds in the Crystal repository](https://github.com/crystal-lang/crystal/tree/master/samples).
That's my 2C.
I find the concept awesome, and too bad to not be able to use it easily in other projects.
You are still able to integrate the `src` directory transparently via `git subtree`.

**Comment by ysbaddaden** [comment]
I never disagreed with your extract. I just want to keep the current sample in!

BTW it's easy to use c2cr when needed:
https://github.com/runic-lang/compiler/blob/master/Makefile

**Pull request closed without merging**
