### PR TITLE
Fix: remove cc comment in default include directories

### PR DESCRIPTION
**Pull request by olbat**
see https://github.com/crystal-lang/crystal_lib/pull/55

### CODE REVIEW

**Comment by ysbaddaden** [comment]
Good catch. Include directories can be declared as `/usr/include (something)`?

My only concern is using a regular expression when we didn't need it before (i.e. no requirement on PCRE).

**Comment by olbat** [comment]
Yes, apparently it's possible (on macOS at least).

For example:
```
$ uname -a
Darwin macbook.local 17.7.0 Darwin Kernel Version 17.7.0: Thu Jun 21 22:53:14 PDT 2018; root:xnu-4570.71.2~1/RELEASE_X86_64 x86_64

$ clang -E - -v < /dev/null
clang version 6.0.1 (tags/RELEASE_601/final)
Target: x86_64-apple-darwin17.7.0
Thread model: posix
InstalledDir: /usr/local/bin
 "/usr/local/Cellar/llvm/6.0.1/bin/clang-6.0" -cc1 ...
clang -cc1 version 6.0.1 based upon LLVM 6.0.1 default target x86_64-apple-darwin17.7.0
#include "..." search starts here:
#include <...> search starts here:
 /usr/local/include
 /usr/local/Cellar/llvm/6.0.1/lib/clang/6.0.1/include
 /usr/include
 /System/Library/Frameworks (framework directory)
 /Library/Frameworks (framework directory)
End of search list.
...
```

No problem for the regular expression, I'll do another version without it.

**Comment by olbat** [comment]
Done!

**Comment by ysbaddaden** [comment]
Thanks!

**Pull request merged**
